name: CI

on: push

jobs:
  run-linters:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm ci

      - name : Run test
        run: npm run prepublishOnly